/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.web.controllers;

import java.util.ArrayList;
import java.util.List;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.example.business.User;
import com.example.web.exception.ServerError;

@Controller
public class HomeController {
    List<User> users = new ArrayList<>();

    @RequestMapping("/")
    public String sayHello(Model model) {
        model.addAttribute("name", "Yaffa");
        return "index"; // This corresponds to the view name
    }

    @PostMapping(path = "/user", consumes = "application/json")
    public ResponseEntity createUser(@RequestBody User user) {
        // Simulate saving the user to the database
        System.out.println("SAVING USER:");
        System.out.println(user.getName() + " " + user.getAge());
        users.add(user);

        return new ResponseEntity(HttpStatus.OK);
    }

    @GetMapping("/users")
    @ResponseBody
    public List<User> getUsers() {
        return users;
    }

    @GetMapping("/servererror")
    @ResponseBody
    public String serverError(@RequestParam String val) throws ServerError {
        if(val.equals("problems")) throw new ServerError();
        return "something";
    }
   
}